"""initial schema

Revision ID: 55eb15843c97
Revises:
Create Date: 2026-09-16 01:23:54.804412

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "55eb15843c97"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_methods",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "jazzcash",
                "easypaisa",
                "nayapay",
                "raast",
                "bank_iban",
                name="payment_method_type",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("account_title", sa.String(length=120), nullable=False),
        sa.Column("account_identifier", sa.String(length=60), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_methods")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("client", "admin", name="user_role", native_enum=False, length=10),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("actor_user_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=60), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column(
            "before",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "after",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_log_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_audit_log_actor_user_id"), ["actor_user_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_audit_log_created_at"), ["created_at"], unique=False)

    op.create_table(
        "clients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("business_name", sa.String(length=200), nullable=False),
        sa.Column("contact_info", sa.String(length=500), nullable=True),
        sa.Column("pricing_model", sa.String(length=30), nullable=False),
        sa.Column("base_fee", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("performance_fee_pct", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "config_overrides",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_clients_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clients")),
        sa.UniqueConstraint("user_id", name=op.f("uq_clients_user_id")),
    )
    op.create_table(
        "ad_data_uploads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("file_sha256", sa.String(length=64), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.Column("date_range_start", sa.Date(), nullable=True),
        sa.Column("date_range_end", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "uploaded",
                "validated",
                "failed",
                name="upload_status",
                native_enum=False,
                length=10,
            ),
            nullable=False,
        ),
        sa.Column(
            "validation_report",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_ad_data_uploads_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ad_data_uploads")),
    )
    with op.batch_alter_table("ad_data_uploads", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ad_data_uploads_client_id"), ["client_id"], unique=False
        )

    op.create_table(
        "invoices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("invoice_number", sa.String(length=20), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("base_fee", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("suggested_recovered_waste", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("confirmed_recovered_waste", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("performance_fee", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("amount_paid", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "issued",
                "payment_submitted",
                "paid",
                "void",
                name="invoice_status",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("confirmed_by", sa.Integer(), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_invoices_client_id_clients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["confirmed_by"],
            ["users.id"],
            name=op.f("fk_invoices_confirmed_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoices")),
        sa.UniqueConstraint("invoice_number", name=op.f("uq_invoices_invoice_number")),
    )
    with op.batch_alter_table("invoices", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_invoices_client_id"), ["client_id"], unique=False)
        batch_op.create_index(
            "ix_invoices_client_period", ["client_id", "period_start"], unique=False
        )

    op.create_table(
        "analysis_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("upload_id", sa.Integer(), nullable=False),
        sa.Column(
            "config_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "done",
                "failed",
                name="run_status",
                native_enum=False,
                length=10,
            ),
            nullable=False,
        ),
        sa.Column(
            "review_status",
            sa.Enum(
                "pending",
                "approved",
                "rejected",
                name="review_status",
                native_enum=False,
                length=10,
            ),
            nullable=False,
        ),
        sa.Column("headline_waste", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("reviewed_by", sa.Integer(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_analysis_runs_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
            name=op.f("fk_analysis_runs_reviewed_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["upload_id"],
            ["ad_data_uploads.id"],
            name=op.f("fk_analysis_runs_upload_id_ad_data_uploads"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_runs")),
    )
    with op.batch_alter_table("analysis_runs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_analysis_runs_client_created", ["client_id", "created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_analysis_runs_client_id"), ["client_id"], unique=False)

    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("invoice_id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column(
            "method_type",
            sa.Enum(
                "jazzcash",
                "easypaisa",
                "nayapay",
                "raast",
                "bank_iban",
                name="payment_method_type",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("transaction_ref", sa.String(length=80), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("paid_at", sa.Date(), nullable=False),
        sa.Column("proof_file_path", sa.String(length=500), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "confirmed",
                "rejected",
                name="payment_status",
                native_enum=False,
                length=10,
            ),
            nullable=False,
        ),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("reviewed_by", sa.Integer(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_payments_client_id_clients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
            name=op.f("fk_payments_invoice_id_invoices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
            name=op.f("fk_payments_reviewed_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
        sa.UniqueConstraint("method_type", "transaction_ref", name="uq_payments_method_ref"),
    )
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_payments_client_id"), ["client_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_payments_invoice_id"), ["invoice_id"], unique=False)

    op.create_table(
        "waste_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("upload_id", sa.Integer(), nullable=False),
        sa.Column("dimension", sa.String(length=30), nullable=False),
        sa.Column("total_spend", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("total_wasted_spend", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("benchmark_cpa", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_waste_reports_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["analysis_runs.id"],
            name=op.f("fk_waste_reports_run_id_analysis_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["upload_id"],
            ["ad_data_uploads.id"],
            name=op.f("fk_waste_reports_upload_id_ad_data_uploads"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_waste_reports")),
    )
    with op.batch_alter_table("waste_reports", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_waste_reports_client_id"), ["client_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_waste_reports_run_id"), ["run_id"], unique=False)

    op.create_table(
        "recommendations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("report_id", sa.Integer(), nullable=False),
        sa.Column("dimension", sa.String(length=30), nullable=False),
        sa.Column("segment_name", sa.String(length=100), nullable=False),
        sa.Column("current_spend", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("recommended_cut", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["waste_reports.id"],
            name=op.f("fk_recommendations_report_id_waste_reports"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recommendations")),
    )
    with op.batch_alter_table("recommendations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_recommendations_report_id"), ["report_id"], unique=False
        )

    op.create_table(
        "segment_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("report_id", sa.Integer(), nullable=False),
        sa.Column("segment_value", sa.String(length=100), nullable=False),
        sa.Column("spend", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("impressions", sa.Integer(), nullable=False),
        sa.Column("clicks", sa.Integer(), nullable=False),
        sa.Column("conversions", sa.Integer(), nullable=False),
        sa.Column("revenue", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("cpa", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("is_significant", sa.Boolean(), nullable=False),
        sa.Column("is_flagged", sa.Boolean(), nullable=False),
        sa.Column("wasted_spend", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["waste_reports.id"],
            name=op.f("fk_segment_metrics_report_id_waste_reports"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_segment_metrics")),
    )
    with op.batch_alter_table("segment_metrics", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_segment_metrics_report_id"), ["report_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("segment_metrics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_segment_metrics_report_id"))

    op.drop_table("segment_metrics")
    with op.batch_alter_table("recommendations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recommendations_report_id"))

    op.drop_table("recommendations")
    with op.batch_alter_table("waste_reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_waste_reports_run_id"))
        batch_op.drop_index(batch_op.f("ix_waste_reports_client_id"))

    op.drop_table("waste_reports")
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_payments_invoice_id"))
        batch_op.drop_index(batch_op.f("ix_payments_client_id"))

    op.drop_table("payments")
    with op.batch_alter_table("analysis_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_analysis_runs_client_id"))
        batch_op.drop_index("ix_analysis_runs_client_created")

    op.drop_table("analysis_runs")
    with op.batch_alter_table("invoices", schema=None) as batch_op:
        batch_op.drop_index("ix_invoices_client_period")
        batch_op.drop_index(batch_op.f("ix_invoices_client_id"))

    op.drop_table("invoices")
    with op.batch_alter_table("ad_data_uploads", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ad_data_uploads_client_id"))

    op.drop_table("ad_data_uploads")
    op.drop_table("clients")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_log_created_at"))
        batch_op.drop_index(batch_op.f("ix_audit_log_actor_user_id"))

    op.drop_table("audit_log")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    op.drop_table("payment_methods")
    # ### end Alembic commands ###
