"""analysis run account total spend

Revision ID: dabea491354c
Revises: 55eb15843c97
Create Date: 2026-09-18 00:00:46.732293

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dabea491354c"
down_revision: str | Sequence[str] | None = "55eb15843c97"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("analysis_runs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("account_total_spend", sa.Numeric(precision=14, scale=2), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("analysis_runs", schema=None) as batch_op:
        batch_op.drop_column("account_total_spend")

    # ### end Alembic commands ###
